#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
# - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    drop-first: true
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml

app:
  crypto:
    key: ${APP_CRYPTO_KEY}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}