#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
# - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    drop-first: true
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.xml

app:
  crypto:
    key: 8Hy/NpB0VqQKWAvrdkRADcATvs14obOYwokw19r0PYY=

jwt:
  secret: mySecretKeyForJWT12345678901234567890
  expiration: 86400000